version: '3.3'

services:
  postgres:
    container_name: yuniqua-db
    build:
      context: ./server/database/
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_EXPOSE_PORT}:5432'

  redis:
    image: redis:latest
    container_name: yuniqua-session
    env_file: .env
    ports:
      - '${REDIS_PORT}:6379'

  server:
    container_name: yuniqua-server
    build:
      context: ./server/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '${SERVER_PORT}:5000'
    depends_on:
      - postgres
      - redis
