apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuniqua-db-deploy
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
      metadata:
        name: db-T
        labels:
          app: postgres
      spec:
        containers:
          - name: yuniqua-db
            image: docker.io/library/yuniqua-db:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP