apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuniqua-server-deploy
  labels:
    type: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      name: server-T
      labels:
        app: flask
    spec:
      containers:
        - name: yuniqua-server
          image: docker.io/library/yuniqua-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: yuniqua-server
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000