version: '3.3'

services:
  postgres:
    image: yuniquadb:latest
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_EXPOSE_PORT}:5432'
  redis:
    image: redis:latest
    env_file: .env
    ports:
      - '${REDIS_PORT}:6379'
